### ISSUE TITLE
libgmp3-dev gets installed twice in .travis.yml file

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-oauth-server#287]
Noticed this while doing the #fxa-bots tweak and now cannot unsee. #seesomethingsaysomething

```yaml
 before_install:
   - sudo apt-get install libgmp3-dev
   - ...
 
 before_script:
   - ...
   - sudo apt-get install libgmp3-dev
```
